
spring:
  mail:
    host: smtp.163.com
    username: wedjg2019@163.com
    password: admin123
    default-encoding: UTF-8
    fromMail:
        addr: wedjg2019@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: Spring-boot-rabbitmq
  rabbitmq:
    host: 192.168.184.128
    port: 5672
    username: admin
    password: admin

logging:
  config:
    classpath: logback.xml
